---
abstract: 'Synchronize books in plain text format.'
author:
  - 'Andre Santos <andrefs@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Perfide-BookSync
provides:
  Text::Perfide::BookSync:
    file: lib/Text/Perfide/BookSync.pm
    version: 0.01_06
requires:
  HTML::Auto: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_06
